package observer;

public enum EventType {
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    DECORATION_CREATED,
    DECORATION_UPDATED,
    DECORATION_DELETED,
    CLUE_CREATED,
    CLUE_UPDATED,
    CLUE_DELETED
}
